# Generated by Django 6.0.3 on 2026-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0002_category_inventoryitem_low_stock_threshold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
