# Generated by Django 6.0.3 on 2026-03-28 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0004_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocklog",
            name="change_amount",
        ),
        migrations.RemoveField(
            model_name="stocklog",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="stocklog",
            name="reason",
        ),
        migrations.AddField(
            model_name="stocklog",
            name="action",
            field=models.CharField(default="Legacy Entry", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocklog",
            name="details",
            field=models.TextField(default="Legacy Entry"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stocklog",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_api.inventoryitem",
            ),
        ),
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_details", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
