# Generated by Django 6.0.3 on 2026-03-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_api",
            "0005_remove_stocklog_change_amount_remove_stocklog_notes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocklog",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory_api.inventoryitem",
            ),
        ),
    ]
