# Generated by Django 6.0.3 on 2026-03-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_api", "0006_alter_stocklog_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklog",
            name="item_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
