name: Django CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install and Run
        shell: bash
        run: |
          # Go into the folder where requirements.txt and manage.py actually are
          cd InvManSys-Backend
          
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          
          export SECRET_KEY="ci-test-key"
          export SENDGRID_API_KEY="SG.fake"
          
          coverage run manage.py test inventory_api
          coverage report --fail-under=80